<script>
var FAULTS = [

{id:"f1", title:"Write through a fresh pointer",
context:"A driver allocates a config struct from a pool, and before it's initialised, a bug writes through it early. The MPU has a no-access region covering address 0.",
regs:{PC:"0x08003C1A", LR:"0xFFFFFFF9", SP:"0x2000FE40", CFSR:"0x00000082", ADDR:"0x00000004"},
decode:["CFSR bits [7:0] = MMFSR = 0x82","bit 1 (DACCVIOL) = 1 \u2192 data access violation","bit 7 (MMARVALID) = 1 \u2192 MMFAR holds the faulting address","MMFAR = 0x00000004 \u2192 a write near address zero"],
options:[
  "A stack overflow corrupted the return address",
  "A write through an uninitialised or null pointer, caught by the MPU's guard region at address 0",
  "The watchdog expired and reset the core",
  "An unaligned access on a part that doesn't support it"],
answerIdx:1,
explain:"MMARVALID tells you the faulting address register is meaningful, and it points at address 4 \u2014 almost certainly a null struct pointer plus a small member offset. This is exactly what the address-zero MPU guard exists to catch: without it, this write would have silently corrupted whatever flash byte happened to sit there.",
related:"faults"},

{id:"f2", title:"Stack guard region trips",
context:"A task with an MPU-enforced stack guard hard-faults deep inside a call chain, at a line that reads a local variable with no unusual code around it.",
regs:{PC:"0x08004F02", LR:"0x08004ECD", SP:"0x2000BFF8", CFSR:"0x00000082", ADDR:"0x2000BFF4"},
decode:["MMFSR bit 1 (DACCVIOL) = 1","MMARVALID = 1, MMFAR = 0x2000BFF4","Faulting address sits just below this task's stack region as configured in the MPU"],
options:[
  "A NULL pointer dereference",
  "An interrupt priority misconfiguration",
  "Stack overflow: the deepest call's locals pushed SP past the guard region below the stack",
  "A flash wait-state misconfiguration"],
answerIdx:2,
explain:"The faulting address sits immediately below the stack's normal range, which is exactly where a guard region lives. The write that faulted wasn't wrong on its own \u2014 it was simply the instruction that finally pushed SP one word too far. Without the guard, this would have quietly overwritten whatever sits below the stack instead of faulting cleanly here.",
related:"faults"},

{id:"f3", title:"No fault status at all",
context:"On a Cortex-M0+ board, the device hard-faults on boot after a change to a struct layout. Reading CFSR gives 0x00000000 no matter what.",
regs:{PC:"0x08000148", LR:"0xFFFFFFFF", SP:"0x20002000", CFSR:"n/a on this core", HFSR:"0x40000000"},
decode:["Cortex-M0/M0+ has no MMFSR, BFSR, or UFSR \u2014 only a single HardFault, no fault detail registers","HFSR bit 30 (FORCED) = 1 \u2192 an escalated fault, but with no sub-detail available","The struct layout change is the only clue you have without extra instrumentation"],
options:[
  "The fault information was cleared before you could read it",
  "This core class has no detailed fault status registers \u2014 the struct change most likely introduced unaligned access",
  "CFSR is only valid after a soft reset",
  "The debugger is not connected correctly"],
answerIdx:1,
explain:"M0 and M0+ do not implement the fault status registers that M3 and above have \u2014 there's no MMFSR, BFSR or UFSR to read, which is why CFSR is unavailable rather than zeroed by something. Given the trigger was a struct layout change, an unaligned word access from a member that's no longer 4-byte aligned is the leading suspect, and on this core class you'd need to bisect the change or add manual diagnostics rather than read a register for the answer.",
related:"align2"},

{id:"f4", title:"Call through a stale function pointer",
context:"A callback table entry was freed and the memory reused for an unrelated buffer. Later, calling through the stale entry faults.",
regs:{PC:"0x2000A104", LR:"0x08006DF0", SP:"0x2000FE10", CFSR:"0x00020000"},
decode:["CFSR bits [25:16] = UFSR = 0x0002","bit 17 of CFSR (UFSR bit 1, INVSTATE) = 1 \u2192 invalid state \u2014 an attempt to execute Thumb-invalid or ARM-mode code","Faulting PC (0x2000A104) is inside RAM, not flash"],
options:[
  "The stack overflowed into the heap",
  "A watchdog reset was misdiagnosed as a HardFault",
  "The core tried to execute code at a RAM address that no longer holds a valid function \u2014 a stale function pointer",
  "A peripheral clock was never enabled"],
answerIdx:2,
explain:"The faulting PC is a RAM address, not a flash address \u2014 code doesn't legitimately execute from RAM in ordinary code, and INVSTATE indicates the core tried to interpret whatever bytes are there as an instruction stream and failed. This is the classic signature of a function pointer that outlived the object it pointed into.",
related:"funcptr"},

{id:"f5", title:"Bootloader forgot to move the vector table",
context:"A bootloader jumps to an application at a non-zero flash offset. The application's own interrupts appear to do nothing \u2014 or fire the bootloader's old handlers.",
regs:{PC:"application code, running normally", ISSUE:"an enabled application interrupt does not call the application's handler"},
decode:["No fault occurs \u2014 this is a silent misbehaviour, not a crash","SCB->VTOR still points at the bootloader's vector table after the jump","The core dispatches through whatever VTOR currently says, regardless of where main() is running"],
options:[
  "The interrupt priority was left at its reset value",
  "SCB->VTOR was never updated to the application's vector table before or after the jump",
  "The application's interrupts were never enabled in the NVIC",
  "The application's clock configuration disabled the peripheral"],
answerIdx:1,
explain:"VTOR is independent of where the CPU happens to be executing \u2014 it's a separate register telling the core where the vector table lives, and a bootloader jump does not change it automatically. Left unset, every interrupt still dispatches through the bootloader's table, running its handlers, or the bootloader's default handler, instead of the application's.",
related:"bootloader"},

{id:"f6", title:"Division inside a signal-processing routine",
context:"A DSP-style scaling routine occasionally hard-faults only on certain sensor readings, with DIV_0_TRP enabled in the configuration register.",
regs:{PC:"0x08007A22", LR:"0x08007A02", SP:"0x2000D200", CFSR:"0x02000000"},
decode:["CFSR bits [25:16] = UFSR = 0x0200","bit 9 of UFSR (DIVBYZERO) = 1"],
options:[
  "A misaligned load in the same function",
  "An integer division where the divisor evaluated to zero for that particular input",
  "A stack overflow triggered during the calculation",
  "The ADC returned an out-of-range value that overflowed a buffer"],
answerIdx:1,
explain:"DIVBYZERO in UFSR is unambiguous once DIV_0_TRP is enabled \u2014 the hardware faults instead of silently returning zero the way it would by default. The fix is at the call site: validate the divisor (very often a calibration or delta value that can legitimately be zero for some inputs) before dividing, not after.",
related:"errors"},

{id:"f7", title:"Executing from a data region",
context:"An MPU region marks a DMA buffer as no-execute (XN) for defence in depth. A buffer-overflow bug elsewhere corrupts a function pointer to point into that buffer, and the resulting call faults immediately rather than running attacker- or corruption-controlled code.",
regs:{PC:"0x20001040", CFSR:"0x00010001"},
decode:["MMFSR bit 0 (IACCVIOL) = 1 \u2192 instruction access violation","MMFSR bit 16 region \u2014 the fault is on an instruction fetch, not a data access","Faulting PC sits inside a region configured as XN (execute-never)"],
options:[
  "The stack pointer was corrupted by an interrupt during a critical section",
  "The core attempted to fetch and execute code from a region explicitly marked non-executable",
  "A double free corrupted the heap allocator's metadata",
  "The watchdog window was violated"],
answerIdx:1,
explain:"IACCVIOL specifically means the violation happened on an instruction fetch. This is the MPU doing exactly the job an XN region is configured for: even though something upstream corrupted a function pointer into this buffer, marking data memory non-executable turns an otherwise silent hijack into an immediate, diagnosable fault.",
related:"faults"},

{id:"f8", title:"Random resets with no fault log",
context:"A device resets sporadically in the field. The fault-logging code, which saves CFSR and PC to a no-init region on HardFault, has never recorded anything.",
regs:{RCC_CSR_or_RSTSRC:"IWDGRSTF = 1 (independent watchdog reset flag set)", CFSR:"never populated"},
decode:["The fault handler's noinit log is empty across every occurrence","The MCU's own reset-cause register shows the watchdog reset flag set, not a fault-derived reset"],
options:[
  "The fault logging code has a bug and silently fails",
  "This was never a HardFault \u2014 the watchdog itself reset the device, which HardFault logging cannot see",
  "The noinit section was accidentally cleared",
  "CFSR should be checked before the watchdog flag, not after"],
answerIdx:1,
explain:"A watchdog reset does not go through HardFault_Handler at all \u2014 it's a completely separate reset path, so fault-log code triggered from HardFault has nothing to record. The reset-cause register (RCC_CSR or equivalent) is the correct place to look, and it directly shows the watchdog flag set. This is as much a lesson in knowing which failure produces which evidence as it is about the bug itself.",
related:"timers"},

{id:"f9", title:"Peripheral write with the clock still gated",
context:"Firmware configures a peripheral immediately after reset and the configuration silently has no effect \u2014 no fault, register just reads back its reset value.",
regs:{PC:"application continues normally", ISSUE:"register write appears to do nothing"},
decode:["No fault: writes to a peripheral with a gated clock are typically just ignored by the bus, not faulted","RCC (or equivalent clock-enable register) for this peripheral was never set before the configuration write"],
options:[
  "The register is read-only and was never writable",
  "The peripheral's clock was never enabled before the write, so the write had nowhere to go",
  "The write happened during a critical section and was rolled back",
  "The linker placed the peripheral struct at the wrong address"],
answerIdx:1,
explain:"Most peripherals are clock-gated off at reset for power reasons, and a bus write to a peripheral with no clock typically just doesn't take \u2014 no fault, no error, the register simply keeps its reset value. This is why the very first line touching any peripheral should be its clock enable, followed by a read-back to confirm the enable itself has taken effect.",
related:"clocks"},

{id:"f10", title:"Unaligned access on a part that tolerates it \u2014 until it doesn't",
context:"Code that casts a byte buffer offset by one to a uint32_t pointer works fine on a Cortex-M4 board and hard-faults on an M0+ variant of the same product line.",
regs:{PC:"0x08002C10 (M0+)", CFSR:"n/a on M0/M0+", HFSR:"0x40000000"},
decode:["M4: tolerates unaligned single-word loads/stores in hardware by default","M0/M0+: any unaligned word access is a hard fault, unconditionally, with no detailed status register","Root cause in the source is the same on both parts \u2014 only the visible behaviour differs"],
options:[
  "The M0+ board has a hardware defect",
  "The code relies on unaligned access tolerance that only M4 and above provide; it was always undefined behaviour",
  "The M4 board is misconfigured and should also be faulting",
  "This is a compiler bug specific to the M0+ toolchain"],
answerIdx:1,
explain:"Casting an offset byte pointer to a wider type and dereferencing it assumes the resulting address is properly aligned, which the code never actually checked. M4 happens to tolerate the resulting unaligned single-word access in hardware; M0+ does not and faults immediately. Both behaviours are consistent with the code being undefined \u2014 one target just told you sooner.",
related:"align2"}
];
</script>
